apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploader-pvc
  namespace: uploader-app
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: gp2-csi
  resources:
    requests:
      storage: 20Gi
