apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: clusters-eu-us
  namespace: rhacm-apps
spec:
  clusterConditions:
    - type: "ManagedClusterConditionAvailable"
      status: "True"
  clusterSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - "eu-cluster"
      - "us-cluster"
