apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: scribe-configs-application
  namespace: uploader-app 
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - scribe-configs-cluster-eu
      - scribe-configs-cluster-us
