apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scribe-leader-election-rolebinding
  namespace: scribe-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scribe-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: scribe-system
