apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: scribe-controller-manager-metrics-service
  namespace: scribe-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP
