apiVersion: scribe.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: uploader-pvc 
  namespace: uploader-app
spec:
  rsync:
    serviceType: ClusterIP
    copyMethod: None 
    destinationPVC: uploader-pvc
    sshKeys: scribe-key
