apiVersion: scribe.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: uploader-pvc 
  namespace: uploader-app
spec:
  sourcePVC: uploader-pvc
  trigger:
    schedule: "*/2 * * * *"
  rsync:
    sshKeys: scribe-key
    address: a42e86e2cda3f423691ac101a7d19c38-475e81bca861123f.elb.us-east-2.amazonaws.com 
    copyMethod: None
